### ISSUE TITLE
Do we use the code inside 04.multi-core-sample folder? 

### ISSUE THREAD

**Issue by hongson23** [JimmyLauren/yolo5_caffe_hisi3559#3]
Thank you for sharing the code, I see inside folder 04.multi-core-sample contains yolov5 implementation, it's very different from the one you instruct
Where is the correct guide?
![image](https://user-images.githubusercontent.com/4011696/223680183-0e8f5ad1-ea6d-48b4-8bcc-732bb8c14295.png)

![image](https://user-images.githubusercontent.com/4011696/223680453-c8dd942c-f5d1-47ed-a760-a192bbb37871.png)

**Comment by hongson23** [comment]
@JimmyLauren 
pls take a  look

**Comment by liujianisme** [comment]
Hi, there are 2 postprocess functions in this code. the one is "yolo_result_process" and the other is modified official code. I mainly use the modified official code.

**Comment by hongson23** [comment]
Hi @JimmyLauren 
Thank for your answers,
I applied your modified code but received wrong results, lot of bbox with confidences are 1  

![image_2023-03-14_16-57-34](https://user-images.githubusercontent.com/4011696/224964687-3215b46e-a65b-417b-b606-9ce6d6db1d3b.png)

![image_2023-03-14_16-59-34](https://user-images.githubusercontent.com/4011696/224965211-847cc29f-5c19-4075-b994-0ad067536f35.png)

This is my code, i run successfully yolov3 with Ruyi simulation and yolov5s caffe
![image_2023-03-14_16-24-12](https://user-images.githubusercontent.com/4011696/224956696-a5c579da-c3c5-4972-807a-2032714c58fa.png)
![image_2023-03-14_16-43-23](https://user-images.githubusercontent.com/4011696/224961088-19446a16-61dd-4bc7-abd3-40e5c95bf0ba.png)
![image_2023-03-14_16-25-41](https://user-images.githubusercontent.com/4011696/224956909-c4bfd87b-5eec-4c89-8ab7-17bb1c905f31.png)
![image_2023-03-14_16-26-20](https://user-images.githubusercontent.com/4011696/224956926-587e2085-3c49-4d85-9491-de876434ba35.png)

I deleted reshape layer and permute layer, I did not modified them, so it is OK?
Can you give me some suggestions?

**Comment by hongson23** [comment]
I modified yolov3 code post-process following your guide but it seem to be existing some mistakes 
please take a look and give me some comments,
i am looking forward to hearing from you
thanks

**Comment by liujianisme** [comment]
Is your model parameters settings correct in function SAMPLE_SVP_NNIE_Yolov3_SoftwareInit? In addition, the confidence calculation in yolov3 and yolov5 is a little bit different. I put the change in added image.
![图片](https://user-images.githubusercontent.com/15936220/225225395-67b31878-919e-4d73-a68c-006a734e4b9f.png)

**Comment by hongson23** [comment]
thank @JimmyLauren ,
Can you give me your caffe model and nnie .wk model which were trained with 2 classes?
I would like to reproduce your results 
about NNIE .wk model, Can you help me convert to simulation in Ruyi studio or convert to HI3516DV300 or HI3516AV300 chipset
thank you so much!

**Comment by hongson23** [comment]
hello @JimmyLauren ,
thank you very much for notes and contributions
I run successfully yolov5s on hisilicon chipset. 
best

**Comment by liujianisme** [comment]
Glad to hear that.
